[kafka]
# brokers = [ "localhost:9092" ]
# groupid = "group01"
# topics = [ "test" ]
# format = "telegraf_json"

# [[filters]] // Not yet implemented
# name = "blacklist_filter"
# configfile = "blacklist_filter.conf"
# enabled = false

# [[filters]]
# name = "whitelist_filter"
# configfile = "whitelist_filter.conf"
# enabled = false

[elasticsearch]
# url = "http://127.0.0.1:9200?cluster.name=my-application"
# template = "telegraf_json"
# prefix = "metricpipe"
# batchSize = 500
# flushInterval = "2s"
# workers = 4
# bufferSize = 2000
# reportInterval = "60s"
# throttleRatio = 0.9
# throttleSleepTime = "50ms"